//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISTEMA.INTEGRADO.V1._0.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entrega
    {
        public int IdOrcamento { get; set; }
        public Nullable<System.DateTime> DataEntrega { get; set; }
        public Nullable<bool> IsEntregue { get; set; }
        public int IdEntrega { get; set; }
        public string tipoEntrega { get; set; }
    
        public virtual Orcamento Orcamento { get; set; }
    }
}
