//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISTEMA.INTEGRADO.V1._0.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdemProducao
    {
        public int IdOrdem { get; set; }
        public int IdProduto { get; set; }
        public Nullable<int> QtdAproduzir { get; set; }
        public Nullable<System.DateTime> DataPedido { get; set; }
        public Nullable<System.DateTime> DataEnviado { get; set; }
        public Nullable<System.DateTime> DataFinalizado { get; set; }
        public string FaseAtual { get; set; }
        public Nullable<int> IdOrcamento { get; set; }
    
        public virtual Produto Produto { get; set; }
    }
}
