//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISTEMA.INTEGRADO.V1._0.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public int IDPedido { get; set; }
        public int IDCadastro { get; set; }
        public int IDProduto { get; set; }
        public Nullable<int> IDProducao { get; set; }
        public Nullable<int> IDCompra { get; set; }
        public int IDFinanceiro { get; set; }
        public int IDEntrega { get; set; }
        public int Quantidade { get; set; }
        public Nullable<decimal> PrecoUnitario { get; set; }
        public string Status { get; set; }
        public System.DateTime DataPedido { get; set; }
    
        public virtual Cadastro Cadastro { get; set; }
    }
}
