//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISTEMA.INTEGRADO.V1._0.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelatorioOrcamentos
    {
        public int NumOrcamento { get; set; }
        public string CpfCliente { get; set; }
        public System.DateTime DataOrcamento { get; set; }
        public string statusCliente { get; set; }
        public string NomeCliente { get; set; }
        public int CodProduto { get; set; }
        public string DescricaoProduto { get; set; }
        public Nullable<double> PrecoUnitario { get; set; }
        public Nullable<System.DateTime> DataEnviado { get; set; }
        public Nullable<bool> IsEntregue { get; set; }
        public Nullable<System.DateTime> DataEntregue { get; set; }
        public Nullable<double> ValorTotal { get; set; }
        public string FaseAtual { get; set; }
        public Nullable<System.DateTime> DataFinalizado { get; set; }
        public Nullable<int> IdOrdem { get; set; }
    }
}
