//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISTEMA.INTEGRADO.V1._0.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transacao
    {
        public Nullable<int> IdPedidoReceber { get; set; }
        public Nullable<double> ValorReceber { get; set; }
        public string Situacao { get; set; }
        public Nullable<double> ValorPago { get; set; }
        public int IdTransacao { get; set; }
        public Nullable<int> idPedidoPagar { get; set; }
    
        public virtual Orcamento Orcamento { get; set; }
        public virtual PedidoCompraSuprimento PedidoCompraSuprimento { get; set; }
    }
}
