//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISTEMA.INTEGRADO.V1._0.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public string Login { get; set; }
        public string Senha { get; set; }
        public string CodTipoAcesso { get; set; }
    
        public virtual TipoAcesso TipoAcesso { get; set; }
    }
}
